run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - revive
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - truncateCmp
      - unnamedResult
  revive:
    rules:
      - name: blank-imports
      - name: exported
      - name: increment-decrement
      - name: var-naming

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
